### ISSUE TITLE
Cron Expression on AWS got me!

### ISSUE THREAD

**Issue by arash-bizcover** [tumido/cron-explained#250]
**Describe the bug**
I don't know if it is a bug or else but:

When using this great extension with the AWS Cloudwatch Rule (i.e. Serverless Framework) the result is not expected.
More specifically, AWS Cron expression (which has 6 fields) uses different numbers for dayOfWeek. 
**e.x. In regular cron, the "dayOfWeek 5" resolves to Friday but in AWS cron expression 5 resolves to Thursday**

**To Reproduce**

**Expected behavior**
It is up to maintainers to either support AWS cron expression or just won't. But I definitely highly recommend if we are not going to support then on 6 fields cron expressions, we show up a warning or pop up about this.
Saying this because I have only seen 6 fields of cron expression with AWS 🙂.

**Screenshots**
**on vs code (cron-explained):**
![image](https://user-images.githubusercontent.com/62287461/131599275-3dc01563-9e8a-49b7-aed3-7484d73d2b77.png)

**on AWS:** 
![image](https://user-images.githubusercontent.com/62287461/131599053-c79c26d0-6fe5-4bf3-9f4f-f69002bc5b80.png)

**Additional context**
I know it is ridiculous behaviour on the AWS side, but as they are not going to change this, and I already faced this issue. I wanted to bring it to your attention.

**Comment by tumido** [comment]
Thank you for filing this issue @arash-bizcover ! :slightly_smiling_face: 

Interesting stuff... I'm affraid AWS may not be alone in this. So let's give users option to modify this behavior. Digging into this, I've noticed that the underlying library used by this extension `cronstrue` already provides some options to configure this. So I'm gonna add new options to this extension as well, so we can feed the library with proper settings.

https://github.com/bradymholt/cronstrue#options

There will be 2 new options for this extension:
- `dayOfWeekStartIndexZero`: Whether to interpret cron expression day of week '1' as Sunday (`false`) or Monday (`true`). In your case, you want 1 to  Sunday, so you can set this option to `false`
- `monthStartIndexZero`: Similar stuff, but for January (is it 0 or 1?)
