### ISSUE TITLE
Support `?` in cron expression

### ISSUE THREAD

**Issue by CWempe** [tumido/cron-explained#64]
I am not sure this is a bug of this extension or a quirk of https://www.openhab.org/.

But _cron-explained_ does not work for the following expression: `0 0 8 ? * * *`

**Error from the extension in VScode**

> Running the contributed command: 'cron-explained.insertComment' failed.

It does work for `0 0 8 * * * *`, but this is not supported by openHAB or even a wrong cron syntax.

![image](https://user-images.githubusercontent.com/1270359/106364216-b36ee700-632d-11eb-9a21-30607ecf7d53.png)

**Error in openHAB**

> Cannot create timer for rule 'Foobar': CronExpression '0 0 8 * * * *' is invalid.

But since I created `0 0 8 ? * * *` with https://www.freeformatter.com/cron-expression-generator-quartz.html I think it is legit and should be supported by this extension.
The website even says '0 0 8 * * * *' is not legit.

However, this extension is very useful. 👍

**Comment by tumido** [comment]
Hi, thank you for raising this to me! This is definitely bug with this extension, you're right.

There are [way too many cron dialects](https://en.wikipedia.org/wiki/Cron#CRON_expression) and this extension currently supports far less than is even supported by the `cronstrue` library I use to provide the transcriptions... I'll fix it. :+1:
